### ISSUE TITLE
Support comparison of SGM entities 

### ISSUE THREAD

**Issue by garrowsmith** [garrowsmith/site-studio-compare#1]
Determine best approach to handle the different structure of the SGM entities and if any flags are required pass/fail custom theme settings, e.g.
* conflict occurs on `uuid+themeid`. 
* an expected customisation is OK.

https://github.com/garrowsmith/site-studio-compare/blob/ceb7b0240168725b287d0bd0b18686f8e74c740b/src/Package/ComparePackage.php#L40

**Example**
* SGM Style Guide (MDS Package)
* SGM Base Theme  (MDS Package) 
** SGM Brand Theme A (Styles Package) OK
** SGM Brand Theme B (Styles Package) OK

**Example SGM settings**
```
  type: cohesion_style_guide
  uuid: 33317a90-8914-446d-b608-9461e5c3902c
```

**An instance of configured SGM theme settings**
```
  type: cohesion_style_guide_manager
  export:
    uuid: 07b90549-0f46-4ede-b7dc-132a9a43499f
    style_guide_uuid: 33317a90-8914-446d-b608-9461e5c3902c
```
